name: Test action workflow
on: 
  push:
    paths:
      - '02_first_project/**' # Only run if our push contains a file in the 02_first_project folder
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./02_first_project
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: ./02_first_project
      - name: Deploy to production
        run: echo "Deploying to production..."
